---

antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "Backup and Snapshots"
      solveButton: false
    - name: module-02
      label: "Infrastructure Reporting"
      solveButton: false
    - name: module-03
      label: "Windows Reporting"
      solveButton: false
    - name: module-04
      label: "Infrastructure Reporting"
      solveButton: false
    - name: module-05
      label: "Windows Reporting"
      solveButton: false

tabs:

  - name: ">_ control"
    url: /wetty
  - name: aap
    url: https://control-${guid}.${domain}/
    external: false
  - name: Gitea
    url: https://gitea-${guid}.${domain}/
