---

antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "Understanding the lab environment"
      solveButton: false
    - name: module-02
      label: "Create gpg keypair to sign projects locally"
      solveButton: false
    - name: module-03
      label: "Sign an empty Ansible project using ansible-sign and validate it in Automation Controller]"
      solveButton: false
    - name: module-04
      label: "Add new project content and validate without signing it"
      solveButton: false
    - name: module-05
      label: "Include the new files in signing manifest and re-sign and verify the project"
      solveButton: false

tabs:

  - name: ">_ control"
    url: /wetty
  - name: aap
    url: https://control-${guid}.${domain}/
    external: false
  - name: Gitea
    url: https://gitea-${guid}.${domain}/
